version: "3.9"
   
services:
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - .env
    restart: unless-stopped
