# Generated by Django 3.1.2 on 2021-05-17 01:09

import datetime

import django.db.models.deletion
from django.db import migrations, models

import abastece.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='inicio pedidos')),
                ('cierre', models.DateTimeField(verbose_name='cierre pedidos')),
                ('aporte_deposito', models.FloatField(default=0)),
                ('aporte_central', models.FloatField(default=0)),
                ('aporte_nodo', models.FloatField(default=0)),
                ('aporte_logistica', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('descripcion', models.TextField(blank=True)),
                ('web', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='Argentina', max_length=200)),
                ('provincia', models.CharField(default='Catamarca', max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'comun'), (2, 'referente')])),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias',
                                               to='abastece.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('envase', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(
                    choices=[('U', 'unidades'), ('g', 'gramos'), ('kg', 'kilogramos'), ('cm3', 'centímetros cúbicos'),
                             ('ml', 'mililitros'), ('l', 'litros'), ('m', 'metros')], max_length=100)),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('costo_financiero', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('costo_postproceso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos',
                                                to='abastece.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVariedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='UNICA', max_length=200)),
                ('disponible', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.producto')),
            ],
            options={
                'verbose_name': 'Variedad de producto',
                'verbose_name_plural': 'Variedades de producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoVariedadCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.IntegerField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.ciclo')),
                ('producto_variedad',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.productovariedad')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_transporte', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_financiero', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_postproceso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.ciclo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.producto')),
            ],
            options={
                'verbose_name': 'Producto en ciclo',
                'verbose_name_plural': 'Productos en ciclo',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp',
                 models.DateTimeField(default=datetime.datetime(2021, 5, 16, 22, 9, 4, 745304), editable=False,
                                      verbose_name='fecha y hora')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.membresia')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.domicilio')),
                ('domicilio_recepcion', models.ForeignKey(blank=True,
                                                          help_text='Solo cuando la mercadería se recibe en un domicilio diferente del de funcionamiento.',
                                                          null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                          related_name='domicilio_recepcion', to='abastece.domicilio')),
            ],
        ),
        migrations.AddField(
            model_name='membresia',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.nodo'),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.pedido')),
                ('producto_variedad_ciclo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.productovariedadciclo')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=abastece.models.get_upload_path)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                               to='abastece.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=abastece.models.get_upload_path)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.contacto')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='abastece.domicilio'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='productos',
            field=models.ManyToManyField(related_name='ciclos', through='abastece.ProductoCiclo',
                                         to='abastece.Producto'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='variedades',
            field=models.ManyToManyField(related_name='ciclos', through='abastece.ProductoVariedadCiclo',
                                         to='abastece.ProductoVariedad'),
        ),
        migrations.AddConstraint(
            model_name='productovariedad',
            constraint=models.UniqueConstraint(fields=('producto', 'descripcion'),
                                               name='unica desc de variedad por producto'),
        ),
        migrations.AddConstraint(
            model_name='productociclo',
            constraint=models.UniqueConstraint(fields=('ciclo', 'producto'), name='unico producto por ciclo'),
        ),
    ]
