# Generated by Django 3.1.2 on 2020-11-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='inicio pedidos')),
                ('cierre', models.DateTimeField(verbose_name='cierre pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('descripcion', models.TextField(blank=True)),
                ('web', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='Argentina', max_length=200)),
                ('provincia', models.CharField(default='Catamarca', max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('envase', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=100)),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_transporte', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_financiero', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVariedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('disponible', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.ciclo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='fecha y hora')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.ciclo')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.domicilio')),
                ('domicilio_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilio_recepcion', to='abastece.domicilio')),
                ('referentes', models.ManyToManyField(to='abastece.Contacto')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.nodo'),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.pedido')),
                ('producto_variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.productovariedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.producto')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abastece.domicilio'),
        ),
    ]
