# Generated by Django 3.1.2 on 2021-05-24 18:45

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abastece', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 15, 45, 35, 301923), editable=False,
                                       verbose_name='fecha y hora'),
        ),
    ]
