# Generated by Django 3.1.2 on 2020-11-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='nombre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
