# Generated by Django 3.1.2 on 2021-05-24 19:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abastece', '0002_auto_20210524_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 16, 25, 37, 994882), editable=False,
                                       verbose_name='fecha y hora'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto_variedad_ciclo'),
                                               name='unico producto por pedido'),
        ),
    ]
