# Generated by Django 3.1.2 on 2020-11-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0002_nodo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'comun'), (2, 'referente')])),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.contacto')),
            ],
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='referentes',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='miembro',
        ),
        migrations.AddField(
            model_name='pedido',
            name='consumidor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='abastece.contacto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Miembro',
        ),
        migrations.AddField(
            model_name='membresia',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastece.nodo'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='miembros',
            field=models.ManyToManyField(through='abastece.Membresia', to='abastece.Contacto'),
        ),
    ]
