# Generated by Django 3.1.2 on 2021-05-27 20:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abastece', '0003_auto_20210524_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 32, 10, 825853), editable=False,
                                       verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='productovariedad',
            name='disponible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productovariedadciclo',
            name='disponible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
