# Generated by Django 3.1.2 on 2021-05-28 22:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abastece', '0004_auto_20210527_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 19, 46, 52, 693250), editable=False,
                                       verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='productovariedad',
            name='disponible',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
