# Generated by Django 3.1.2 on 2021-01-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0004_auto_20201120_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_postproceso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('U', 'unidades'), ('g', 'gramos'), ('kg', 'kilogramos'), ('cm3', 'centímetros cubicos'), ('ml', 'mililitros'), ('l', 'litros'), ('m', 'metros')], max_length=100),
        ),
    ]
