# Generated by Django 3.1.2 on 2021-05-31 14:45

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abastece', '0005_auto_20210528_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 11, 45, 20, 503212), editable=False,
                                       verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
