# Generated by Django 3.1.2 on 2021-06-01 02:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abastece', '0006_auto_20210531_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 23, 31, 54, 21655), editable=False,
                                       verbose_name='fecha y hora'),
        ),
    ]
