# Generated by Django 3.1.2 on 2021-03-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0007_ciclo_variedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagencontacto',
            name='imagen',
            field=models.ImageField(default='borrar', upload_to='contactos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='abastece.producto'),
        ),
    ]
