# Generated by Django 3.1.2 on 2021-03-14 22:12

import abastece.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0008_auto_20210314_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(default='Borrar', upload_to=abastece.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagencontacto',
            name='imagen',
            field=models.ImageField(upload_to=abastece.models.get_upload_path),
        ),
    ]
