# Generated by Django 3.1.2 on 2021-03-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0010_auto_20210314_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_financiero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_postproceso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
