# Generated by Django 3.1.2 on 2021-03-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0011_auto_20210314_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='abastece.contacto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='abastece.contacto'),
        ),
    ]
