# Generated by Django 3.1.2 on 2021-08-28 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abastece', '0011_auto_20210828_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
