# Generated by Django 3.1.2 on 2021-10-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0013_auto_20210907_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_aporte',
            field=models.IntegerField(default=100),
        ),
    ]
