# Generated by Django 3.1.2 on 2021-10-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0014_producto_porcentaje_aporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_aporte',
            field=models.IntegerField(default=100, help_text='El porcentaje de aportes que se aplicará al producto.'),
        ),
    ]
