# Generated by Django 3.1.2 on 2021-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0015_auto_20211022_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cbu_o_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
